# default values
default:
  sfImageTransformPlugin:
    default_adapter: ImageMagick # GD or ImageMagick   use : > find /data/www -wholename "*.thumbs/*" -exec rm -f {} \;   to purge all thumbs generated if change adapter
    default_image:
      mime_type: image/png
      filename: Untitled.png
      width: 100
      height: 100
      color: '#FFFFFF'
    font_dir: /usr/share/fonts/truetype/dejavu
    mime_type:
      auto_detect: false
      library: gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)
